from typing import List, Dict, Any
from datetime import datetime
import asyncpg
import logging
from app.database import get_database
from app.services.utils.retry import retry_async, is_transient_pg_error
from app.services.utils.sanitize import sanitize_path

logger = logging.getLogger(__name__)
db = get_database()

class GeneratorService:
    def __init__(self, deepseek_client, github_client):
        self.deepseek = deepseek_client
        self.github = github_client

    async def _create_job(self, conn: asyncpg.Connection, repo_name: str) -> int:
        row = await conn.fetchrow(
            "INSERT INTO jobs(repo_name, status, created_at) VALUES($1, $2, $3) RETURNING id",
            repo_name, 'pending', datetime.utcnow()
        )
        return row["id"]

    async def _update_job(self, conn: asyncpg.Connection, job_id: int, status: str, repo_url: str | None = None, error: str | None = None):
        await conn.execute(
            "UPDATE jobs SET status=$1, github_repo_url=$2, error=$3, updated_at=$4 WHERE id=$5",
            status, repo_url, error, datetime.utcnow(), job_id
        )

    async def _insert_generated_file(self, conn: asyncpg.Connection, job_id: int, path: str):
        await conn.execute(
            "INSERT INTO generated_files(job_id, path, created_at) VALUES($1, $2, $3)",
            job_id, path, datetime.utcnow()
        )

    async def generate_and_publish(self, requirements: str, repo_name: str, github_username: str, private: bool, description: str):
        async def _work() -> Dict[str, Any]:
            async with db.transaction() as conn:
                job_id = await self._create_job(conn, repo_name)
                await self._update_job(conn, job_id, "running")

                files = await self.deepseek.generate_code(requirements)

                repo_meta = await self.github.create_repository(name=repo_name, private=private, description=description)
                repo_full = repo_meta.get("full_name")
                repo_html = repo_meta.get("html_url")

                owner, repo = repo_full.split("/", 1)
                created_paths: List[str] = []

                for f in files:
                    raw_path = f.get("path")
                    content = f.get("content", "")
                    safe_path = sanitize_path(raw_path)
                    await self.github.put_file(owner=owner, repo=repo, path=safe_path, content=content, message=f"Add {safe_path}")
                    await self._insert_generated_file(conn, job_id, safe_path)
                    created_paths.append(safe_path)

                if "README.md" not in created_paths:
                    readme = f"# {repo_name}\n\nRepository generated by CodeGenMicroservice"
                    await self.github.put_file(owner=owner, repo=repo, path="README.md", content=readme, message="Add README")
                    await self._insert_generated_file(conn, job_id, "README.md")
                    created_paths.append("README.md")

                await self._update_job(conn, job_id, "done", repo_html, None)
                return {"job_id": job_id, "repo_url": repo_html, "created_files": created_paths}

        def retry_on_pg(exc: Exception) -> bool:
            import asyncpg
            if isinstance(exc, asyncpg.PostgresError):
                sqlstate = getattr(exc, "sqlstate", None)
                return is_transient_pg_error(sqlstate)
            return False

        result = await retry_async(
            _work,
            retries=3,
            initial_delay=0.3,
            backoff_factor=2.0,
            retry_exceptions=(asyncpg.PostgresError,),
            retry_on_predicate=retry_on_pg
        )
        return result
