from pydantic import BaseModel, Field, constr
from typing import Annotated, Optional, List
from datetime import datetime
from enum import Enum


# -----------------------------
# Authentication / Token
# -----------------------------
class AuthTokenRequest(BaseModel):
    client_id: str
    client_secret: str

class TokenValidationRequest(BaseModel):
    token: str

class TokenResponse(BaseModel):
    token: str
    client_id: str
    expires_at: str

class TokenValidationResponse(BaseModel):
    valid: bool
    message: str

class AuthenticatedRequest(BaseModel):
    token: str


# -----------------------------
# Enums
# -----------------------------
class JobStatus(str, Enum):
    pending = "pending"
    running = "running"
    done = "done"
    failed = "failed"


# -----------------------------
# Code Generation
# -----------------------------
class GenerateRequest(BaseModel):
    requirements: str = Field(
        ..., min_length=5, description="Description of the requirements for code generation"
    )
    repo_name: str = Field(
        ..., min_length=1, max_length=100, description="Name of the repository to be created on GitHub"
    )
    github_username: str = Field(..., description="GitHub username")
    github_token: str = Field(..., description="GitHub Personal Access Token")
    private: bool = Field(default=True, description="Whether the repository will be private")
    description: Optional[str] = Field(
        default="Generated by CodeGenMicroservice", max_length=255
    )

class GenerateResponse(BaseModel):
    repo_url: str
    created_files: List[str]
    job_id: int


# -----------------------------
# Jobs
# -----------------------------
class JobCreate(BaseModel):
    repo_name: str

class JobUpdate(BaseModel):
    status: JobStatus
    github_repo_url: Optional[str] = None
    error: Optional[str] = None

class JobResponse(BaseModel):
    id: int
    repo_name: str
    status: JobStatus
    github_repo_url: Optional[str] = None
    error: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# -----------------------------
# Generated Files
# -----------------------------
class GeneratedFileCreate(BaseModel):
    job_id: int
    path: str

class GeneratedFileResponse(BaseModel):
    id: int
    job_id: int
    path: str
    created_at: datetime

    class Config:
        from_attributes = True


# -----------------------------
# Authenticated Versions
# -----------------------------
class AuthenticatedGenerateRequest(BaseModel):
    token: str
    requirements: str
    repo_name: str
    github_username: str
    private: bool = True
    description: Optional[str] = None


# -----------------------------
# Utility Responses
# -----------------------------
class HealthCheckResponse(BaseModel):
    status: str
    service: str
    version: str
    authenticated_client: Optional[str] = None

class RootResponse(BaseModel):
    message: str
    version: str
    docs: str
    redoc: str
    authenticated_client: Optional[str] = None

class SuccessResponse(BaseModel):
    message: str

class ErrorResponse(BaseModel):
    detail: str


# -----------------------------
# Pagination / Listing
# -----------------------------
class PaginatedResponse(BaseModel):
    data: List
    page: int
    limit: int
    total: int
    has_next: bool
    has_prev: bool

class JobListResponse(BaseModel):
    jobs: List[JobResponse]
    total_count: int
    page: int
    limit: int

class GeneratedFileListResponse(BaseModel):
    files: List[GeneratedFileResponse]
    total_count: int
    page: int
    limit: int


# -----------------------------
# Validation Errors
# -----------------------------
class ValidationError(BaseModel):
    loc: List[str]
    msg: str
    type: str

class HTTPValidationError(BaseModel):
    detail: List[ValidationError]